// Auto-generated by tb/edge/gen_tile_edge_data.py: p2_edge_4x4_ws_l2
// P2 tile edge case. A/W are CPU/testbench tile-packed streams.
// M_DIM/N_DIM are local tile dimensions; GLOBAL_* records the Conv2D GEMM shape.
`define TEST_NAME "p2_edge_4x4_ws_l2"
`define EDGE_SHAPE "4x4"
`define EDGE_DATAFLOW "ws"
`define EDGE_LANES 2
`define EDGE_STREAM_ELEM_BITS 16
`define EDGE_PACKED_K_GROUPS 5
`define EDGE_PACKED_HIGH_LANE_CONTRIB 1
`define TILE_M 4
`define TILE_N 4
`define M_DIM 4
`define N_DIM 4
`define GLOBAL_M_DIM 64
`define GLOBAL_N_DIM 4
`define K_DIM 9
`define M_BASE 9
`define N_BASE 0
`define BATCH 1
`define CIN 1
`define COUT 4
`define IH 8
`define IW 8
`define OH 8
`define OW 8
`define NUM_RESULTS 16
`define A_WORDS 10
`define W_WORDS 10
`define DRAM_SIZE 8192
`define W_ADDR 32'h00001000
`define A_ADDR 32'h00003000
`define R_ADDR 32'h00005000
`define CTRL 32'h00000001
`define CFG_SHAPE 32'h00000000
`define IS_FP16 0
`define DRAM_HEX "tb/edge/p2_edge_4x4_ws_l2/dram_init.hex"
`define EXPECTED_HEX "tb/edge/p2_edge_4x4_ws_l2/expected.hex"
