// Auto-generated by tb/tile4/gen_tile4_data.py: int8_4x4x4
`define TEST_NAME "int8_4x4x4"
`define M_DIM 4
`define N_DIM 4
`define K_DIM 4
`define NUM_RESULTS 16
`define DRAM_SIZE 1024
`define W_ADDR 32'h00000100
`define A_ADDR 32'h00000140
`define R_ADDR 32'h00000180
`define CTRL 32'h00000011
`define IS_FP16 0
`define DRAM_HEX "tb/tile4/int8_4x4x4/dram_init.hex"
`define EXPECTED_HEX "tb/tile4/int8_4x4x4/expected.hex"
