// =============================================================================
// Auto-generated testbench wrapper for N=16
// Generated by gen_tb.py - DO NOT EDIT
// =============================================================================

`timescale 1ns/1ps

module tb_array_scale;

`define N 16
`include "test_params.vh"

localparam ROWS    = 1;
localparam COLS    = 1;
localparam DATA_W  = 16;
localparam ACC_W   = 32;
localparam CLK_T   = 10;
localparam DRAM_SZ = `DRAM_SIZE;

// NPU AXI-Lite register map
localparam REG_CTRL   = 32'h00;
localparam REG_STATUS = 32'h04;
localparam REG_M_DIM  = 32'h10;
localparam REG_N_DIM  = 32'h14;
localparam REG_K_DIM  = 32'h18;
localparam REG_W_ADDR = 32'h20;
localparam REG_A_ADDR = 32'h24;
localparam REG_R_ADDR = 32'h28;

// ---------------------------------------------------------------------------
// DRAM Model (hardcoded paths - iverilog doesn't expand macros in $readmemh)
// ---------------------------------------------------------------------------
reg [ACC_W-1:0] dram [0:DRAM_SZ-1];
integer dram_i;

initial begin
    for (dram_i = 0; dram_i < DRAM_SZ; dram_i = dram_i + 1)
        dram[dram_i] = 32'h0;
    $readmemh("D:/NPU_prj/tb/array_scale/N16/dram_init.hex", dram);
end

// ---------------------------------------------------------------------------
// Expected results (hardcoded path)
// ---------------------------------------------------------------------------
reg [31:0] expected [0:`NUM_TESTS-1];
integer exp_i;

initial begin
    for (exp_i = 0; exp_i < `NUM_TESTS; exp_i = exp_i + 1)
        expected[exp_i] = 32'h0;
    $readmemh("D:/NPU_prj/tb/array_scale/N16/expected.hex", expected);
end


`include "../../tb_array_scale_body.v"

endmodule
