#!/usr/bin/env python3
# =============================================================================
# gen_tiny_conv_soc_case.py - Build a small .pth-driven SoC Conv2D smoke case.
#
# This intentionally targets the current ~60KB DRAM testbench. It creates a
# quantized tiny Conv2D checkpoint, converts it through pth_to_npu_assets.py,
# emits DRAM init data, and emits RV32I firmware hex that asks the NPU to run
# the converted Conv2D+ReLU layer.
# =============================================================================

import argparse
import json
import sys
from pathlib import Path
from types import SimpleNamespace

THIS_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = THIS_DIR.parents[1]
TB_DIR = PROJECT_ROOT / "tb"
if str(TB_DIR) not in sys.path:
    sys.path.insert(0, str(TB_DIR))

from assemble_soc_test import ANDI, BEQZ, BNE, J, LW, SW, li_insns  # noqa: E402
from pth_to_npu_assets import convert as convert_pth  # noqa: E402


NPU_BASE = 0x02000000
A_ADDR = 0x00001000
W_BASE = 0x00001100
R_ADDR = 0x00001300
MARKER_ADDR = 0x00002000
PASS_MARKER = 0x000000AA
FAIL_MARKER = 0x000000FF
DRAM_WORDS = 15360

REG_CTRL = 0x00
REG_STATUS = 0x04
REG_M_DIM = 0x10
REG_N_DIM = 0x14
REG_K_DIM = 0x18
REG_W_ADDR = 0x20
REG_A_ADDR = 0x24
REG_R_ADDR = 0x28
REG_CONV_IFM_SHAPE = 0x80
REG_CONV_CHANNELS = 0x84
REG_CONV_KERNEL = 0x88
REG_CONV_OUT_SHAPE = 0x8C
REG_CONV_STRIDE_PAD = 0x90
REG_CONV_DILATION = 0x94
REG_BIAS_ADDR = 0x98
REG_QUANT_CFG = 0x9C


def require_torch():
    try:
        import torch  # noqa: WPS433
    except Exception as exc:
        raise SystemExit(
            "PyTorch is required to generate the tiny .pth case. "
            "Install CPU PyTorch with the command in tools/pth/README.md.\n"
            f"Import error: {exc}"
        ) from exc
    return torch


def int8_pack(values):
    words = []
    for idx in range(0, len(values), 4):
        word = 0
        for lane in range(4):
            if idx + lane < len(values):
                word |= (int(values[idx + lane]) & 0xFF) << (8 * lane)
        words.append(word & 0xFFFFFFFF)
    return words


def write_hex(path, words):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        for word in words:
            f.write(f"{word & 0xFFFFFFFF:08x}\n")


def load_hex_words(path):
    words = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                words.append(int(line, 16))
    return words


def tiny_tensors():
    ifm = [
        1, 2, 0, -1,
        3, 1, -2, 2,
        0, 1, 4, 1,
        -1, 2, 1, 3,
    ]
    weights = [
        [
            1, 1, 1,
            1, 1, 1,
            1, 1, 1,
        ],
        [
            1, 0, -1,
            1, 0, -1,
            1, 0, -1,
        ],
    ]
    expected = [
        10, 2,
        8, 2,
        9, 0,
        13, 0,
    ]
    return ifm, weights, expected


def make_checkpoint(out_dir):
    torch = require_torch()
    ifm, weights, expected = tiny_tensors()

    weight_tensor = torch.tensor(weights, dtype=torch.float32).reshape(2, 1, 3, 3)
    scales = torch.tensor([1.0, 1.0], dtype=torch.float64)
    zero_points = torch.tensor([0, 0], dtype=torch.int64)
    qweight = torch.quantize_per_channel(weight_tensor, scales, zero_points, axis=0, dtype=torch.qint8)

    state = {
        "quant.scale": torch.tensor(1.0, dtype=torch.float32),
        "quant.zero_point": torch.tensor(0, dtype=torch.int64),
        "conv.weight": qweight,
        "conv.bias": torch.tensor([0.0, 0.0], dtype=torch.float32),
        "conv.scale": torch.tensor(1.0, dtype=torch.float32),
        "conv.zero_point": torch.tensor(0, dtype=torch.int64),
    }
    pth_path = out_dir / "tiny_conv_int8.pth"
    torch.save({"state_dict": state}, pth_path)

    spec = {
        "name": "tiny_conv_relu_soc_int8",
        "input": {
            "shape": [1, 1, 4, 4],
            "dtype": "int8",
            "layout": "NCHW",
            "scale_key": "quant.scale",
            "zero_point_key": "quant.zero_point",
            "source_preprocess": "fixed tiny NCHW int8 tensor generated by gen_tiny_conv_soc_case.py",
        },
        "layers": [
            {
                "name": "conv0",
                "op": "conv2d",
                "weight": "conv.weight",
                "bias": "conv.bias",
                "stride": [1, 1],
                "padding": [0, 0],
                "dilation": [1, 1],
                "activation": "relu",
            }
        ],
    }
    spec_path = out_dir / "tiny_conv_int8_spec.json"
    with open(spec_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(spec, f, indent=2)

    write_hex(out_dir / "input_nchw_int8.hex", int8_pack(ifm))
    write_hex(out_dir / "expected_acc_int32.hex", expected)
    with open(out_dir / "input_nchw_int8.json", "w", encoding="utf-8", newline="\n") as f:
        json.dump({"shape": [1, 1, 4, 4], "values": ifm}, f, indent=2)
    with open(out_dir / "expected_acc_int32.json", "w", encoding="utf-8", newline="\n") as f:
        json.dump({"shape": [1, 2, 2, 2], "layout": "NHWC row-major words", "values": expected}, f, indent=2)

    return pth_path, spec_path, expected


def write_dram_init(out_dir, plan, input_words):
    dram = [0 for _ in range(DRAM_WORDS)]

    for idx, word in enumerate(input_words):
        dram[(A_ADDR >> 2) + idx] = word

    layer = plan["layers"][0]
    assets = layer["assets"]
    asset_dir = out_dir
    for key, addr_key in (("w_col_hex", "w_addr"), ("bias_int32_hex", "bias_addr")):
        words = load_hex_words(asset_dir / assets[key])
        base = int(assets[addr_key], 0) >> 2
        for idx, word in enumerate(words):
            dram[base + idx] = word

    write_hex(out_dir / "dram_init.hex", dram)


def assemble_firmware(layer, expected):
    regs = layer["registers"]
    insns = []
    labels = {}

    def emit(*words):
        for word in words:
            insns.append(word)

    def label(name):
        labels[name] = len(insns)

    def write_reg(offset, value):
        emit(*li_insns("t1", int(value)))
        emit(SW("t1", "t0", offset))

    def patch_beqz(idx, target_label, rs="t1"):
        offset = (labels[target_label] - idx) * 4
        insns[idx] = BEQZ(rs, offset)

    def patch_bne(idx, target_label, rs1="t1", rs2="t3"):
        offset = (labels[target_label] - idx) * 4
        insns[idx] = BNE(rs1, rs2, offset)

    def patch_j(idx, target_label):
        offset = (labels[target_label] - idx) * 4
        insns[idx] = J(offset)

    label("_start")
    emit(*li_insns("sp", 0x00001000))
    emit(*li_insns("t0", NPU_BASE))

    write_reg(REG_CTRL, 0)
    write_reg(REG_M_DIM, regs["M_DIM"])
    write_reg(REG_N_DIM, regs["N_DIM"])
    write_reg(REG_K_DIM, regs["K_DIM"])
    write_reg(REG_W_ADDR, int(regs["W_ADDR"]))
    write_reg(REG_A_ADDR, A_ADDR)
    write_reg(REG_R_ADDR, R_ADDR)
    write_reg(REG_CONV_IFM_SHAPE, regs["CONV_IFM_SHAPE"])
    write_reg(REG_CONV_CHANNELS, regs["CONV_CHANNELS"])
    write_reg(REG_CONV_KERNEL, regs["CONV_KERNEL"])
    write_reg(REG_CONV_OUT_SHAPE, regs["CONV_OUT_SHAPE"])
    write_reg(REG_CONV_STRIDE_PAD, regs["CONV_STRIDE_PAD"])
    write_reg(REG_CONV_DILATION, regs["CONV_DILATION"])
    write_reg(REG_BIAS_ADDR, int(regs["BIAS_ADDR"]))
    write_reg(REG_QUANT_CFG, regs["QUANT_CFG"])
    write_reg(REG_CTRL, regs["CTRL"])

    label("poll_loop")
    emit(LW("t1", "t0", REG_STATUS))
    emit(ANDI("t1", "t1", 2))
    poll_loop_beqz_idx = len(insns)
    emit(0)

    emit(*li_insns("t2", R_ADDR))
    fail_branches = []
    for idx, value in enumerate(expected):
        emit(LW("t1", "t2", idx * 4))
        emit(*li_insns("t3", value))
        fail_branches.append(len(insns))
        emit(0)

    write_pass_j_idx = len(insns)
    emit(0)

    label("verify_fail")
    emit(*li_insns("t0", MARKER_ADDR))
    emit(*li_insns("t1", FAIL_MARKER))
    emit(SW("t1", "t0", 0))
    end_j_fail = len(insns)
    emit(0)

    label("write_pass")
    emit(*li_insns("t0", MARKER_ADDR))
    emit(*li_insns("t1", PASS_MARKER))
    emit(SW("t1", "t0", 0))

    label("end")
    end_j_end = len(insns)
    emit(0)

    patch_beqz(poll_loop_beqz_idx, "poll_loop")
    for branch_idx in fail_branches:
        patch_bne(branch_idx, "verify_fail")
    patch_j(write_pass_j_idx, "write_pass")
    patch_j(end_j_fail, "end")
    patch_j(end_j_end, "end")
    return insns


def write_params(out_dir, fw_words, expected):
    lines = [
        f"`define PTH_TINY_FW_HEX \"../sim/{out_dir.name}/soc_pth_tiny_conv.hex\"",
        f"`define PTH_TINY_DRAM_HEX \"../sim/{out_dir.name}/dram_init.hex\"",
        f"`define PTH_TINY_FW_WORDS {fw_words}",
        f"`define PTH_TINY_RESULT_BASE 32'h{R_ADDR:08x}",
        f"`define PTH_TINY_MARKER_ADDR 32'h{MARKER_ADDR:08x}",
        f"`define PTH_TINY_RESULT_COUNT {len(expected)}",
    ]
    for idx, value in enumerate(expected):
        lines.append(f"`define PTH_TINY_EXPECTED_{idx} 32'sd{value}")
    with open(out_dir / "soc_pth_tiny_conv_params.vh", "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
        f.write("\n")


def main():
    parser = argparse.ArgumentParser(description="Generate a .pth-driven tiny Conv2D SoC smoke case")
    parser.add_argument("--out-dir", default="sim/pth_tiny_conv", help="Output case directory")
    args = parser.parse_args()

    out_dir = Path(args.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    pth_path, spec_path, expected = make_checkpoint(out_dir)
    convert_pth(
        SimpleNamespace(
            pth=str(pth_path),
            spec=str(spec_path),
            out_dir=str(out_dir),
            mode="OS",
            base_addr=f"0x{W_BASE:08x}",
        )
    )

    with open(out_dir / "model_plan.json", "r", encoding="utf-8") as f:
        plan = json.load(f)
    input_words = load_hex_words(out_dir / "input_nchw_int8.hex")
    write_dram_init(out_dir, plan, input_words)

    insns = assemble_firmware(plan["layers"][0], expected)
    write_hex(out_dir / "soc_pth_tiny_conv.hex", insns)
    write_params(out_dir, len(insns), expected)

    print(f"generated tiny SoC pth case: {out_dir}")
    print(f"firmware words: {len(insns)}")
    print(f"expected: {expected}")


if __name__ == "__main__":
    main()
