#!/usr/bin/env python3
"""Generate 4x4 tile-mode GEMM data for T2.5/T2.6."""

import math
import os
import struct


ROOT = os.path.dirname(os.path.abspath(__file__))


def f32(value):
    return struct.unpack("<f", struct.pack("<f", value))[0]


def f32_word(value):
    return struct.unpack("<I", struct.pack("<f", value))[0]


def fp16_to_float(h):
    sign = -1.0 if (h & 0x8000) else 1.0
    exp = (h >> 10) & 0x1F
    frac = h & 0x03FF
    if exp == 0:
        if frac == 0:
            return -0.0 if sign < 0 else 0.0
        return sign * (frac / 1024.0) * (2.0 ** -14)
    if exp == 0x1F:
        if frac == 0:
            return math.copysign(float("inf"), sign)
        return float("nan")
    return sign * (1.0 + frac / 1024.0) * (2.0 ** (exp - 15))


def float_to_fp16(value):
    if math.isnan(value):
        return 0x7E00
    if math.isinf(value):
        return 0xFC00 if value < 0 else 0x7C00
    if value == 0:
        return 0x8000 if math.copysign(1.0, value) < 0 else 0x0000

    sign = 1 if value < 0 else 0
    value = abs(value)
    exp = int(math.floor(math.log(value, 2)))
    biased = exp + 15

    if biased <= 0:
        mant = round(value / (2.0 ** -24))
        return (sign << 15) | min(int(mant), 0x3FF)
    if biased >= 31:
        return 0xFC00 if sign else 0x7C00

    frac = value / (2.0 ** exp) - 1.0
    mant = round(frac * 1024)
    if mant >= 1024:
        mant = 0
        biased += 1
    if biased >= 31:
        return 0xFC00 if sign else 0x7C00
    return (sign << 15) | (biased << 10) | int(mant)


def pack_int8_lanes(values):
    word = 0
    for lane, value in enumerate(values):
        word |= (value & 0xFF) << (lane * 8)
    return [word]


def pack_fp16_lanes(values):
    return [
        (values[0] & 0xFFFF) | ((values[1] & 0xFFFF) << 16),
        (values[2] & 0xFFFF) | ((values[3] & 0xFFFF) << 16),
    ]


def write_hex(path, words):
    with open(path, "w", encoding="ascii") as f:
        for word in words:
            f.write(f"{word & 0xFFFFFFFF:08x}\n")


def build_dram(a_mat, b_mat, expected, dtype, w_addr, a_addr, r_addr, dram_words):
    dram = [0] * dram_words
    pack_lanes = pack_int8_lanes if dtype == "int8" else pack_fp16_lanes

    for k in range(4):
        w_words = pack_lanes([b_mat[k][c] for c in range(4)])
        a_words = pack_lanes([a_mat[r][k] for r in range(4)])
        for idx, word in enumerate(w_words):
            dram[(w_addr >> 2) + k * len(w_words) + idx] = word
        for idx, word in enumerate(a_words):
            dram[(a_addr >> 2) + k * len(a_words) + idx] = word

    for r in range(4):
        for c in range(4):
            dram[(r_addr >> 2) + r * 4 + c] = 0

    return dram


def int8_expected(a_mat, b_mat):
    out = []
    for r in range(4):
        for c in range(4):
            acc = sum(a_mat[r][k] * b_mat[k][c] for k in range(4))
            out.append(acc & 0xFFFFFFFF)
    return out


def fp16_expected(a_mat, b_mat):
    out = []
    for r in range(4):
        for c in range(4):
            acc = f32(0.0)
            for k in range(4):
                prod_h = float_to_fp16(fp16_to_float(a_mat[r][k]) * fp16_to_float(b_mat[k][c]))
                acc = f32(acc + f32(fp16_to_float(prod_h)))
            out.append(f32_word(acc))
    return out


def emit_case(name, dtype, a_mat, b_mat):
    out_dir = os.path.join(ROOT, name)
    os.makedirs(out_dir, exist_ok=True)

    if dtype == "int8":
        w_addr, a_addr, r_addr = 0x100, 0x140, 0x180
        expected = int8_expected(a_mat, b_mat)
        ctrl = 0x00000011
    else:
        w_addr, a_addr, r_addr = 0x200, 0x280, 0x300
        expected = fp16_expected(a_mat, b_mat)
        ctrl = 0x00000019

    dram = build_dram(a_mat, b_mat, expected, dtype, w_addr, a_addr, r_addr, 1024)
    write_hex(os.path.join(out_dir, "dram_init.hex"), dram)
    write_hex(os.path.join(out_dir, "expected.hex"), expected)

    with open(os.path.join(out_dir, "test_params.vh"), "w", encoding="ascii") as f:
        f.write(f"// Auto-generated by tb/tile4/gen_tile4_data.py: {name}\n")
        f.write('`define TEST_NAME "' + name + '"\n')
        f.write("`define M_DIM 4\n")
        f.write("`define N_DIM 4\n")
        f.write("`define K_DIM 4\n")
        f.write("`define NUM_RESULTS 16\n")
        f.write("`define DRAM_SIZE 1024\n")
        f.write(f"`define W_ADDR 32'h{w_addr:08x}\n")
        f.write(f"`define A_ADDR 32'h{a_addr:08x}\n")
        f.write(f"`define R_ADDR 32'h{r_addr:08x}\n")
        f.write(f"`define CTRL 32'h{ctrl:08x}\n")
        f.write(f"`define IS_FP16 {1 if dtype == 'fp16' else 0}\n")
        f.write(f'`define DRAM_HEX "tb/tile4/{name}/dram_init.hex"\n')
        f.write(f'`define EXPECTED_HEX "tb/tile4/{name}/expected.hex"\n')

    print(f"{name}: wrote {out_dir}")


def main():
    int8_a = [
        [3, -2, 5, 7],
        [-1, 4, 0, 6],
        [8, -3, 2, -5],
        [0, 9, -4, 1],
    ]
    int8_b = [
        [2, -1, 3, 0],
        [5, 4, -2, 1],
        [-3, 6, 1, -4],
        [7, 0, -5, 2],
    ]

    fp16_a_float = [
        [1.0, -2.0, 0.5, 1.5],
        [-1.5, 0.25, 2.0, -0.5],
        [0.75, 1.25, -1.0, 2.0],
        [2.5, -0.75, 0.125, -1.25],
    ]
    fp16_b_float = [
        [0.5, -1.0, 2.0, 1.5],
        [1.25, 0.75, -0.5, 2.0],
        [-1.5, 2.5, 0.25, -0.75],
        [2.0, -0.25, 1.0, 0.5],
    ]
    fp16_a = [[float_to_fp16(x) for x in row] for row in fp16_a_float]
    fp16_b = [[float_to_fp16(x) for x in row] for row in fp16_b_float]

    emit_case("int8_4x4x4", "int8", int8_a, int8_b)
    emit_case("fp16_4x4x4", "fp16", fp16_a, fp16_b)


if __name__ == "__main__":
    main()
