# =============================================================================
# run_array_scale.ps1 - K-depth scale verification on 1x1 PE testbench
#
# Tests ROWS=1, COLS=1 with K=N for N=4,8,16,32 under INT8/FP16 × WS/OS modes.
# Total: 16 test cases across 4 K-depth configurations.

#
# Depends on Bug 5 fix (npu_ctrl: S_WB_WAIT no longer re-asserts dma_r_start)
#            and Bug 6 fix (npu_dma: r_pending mechanism for OS mode timeout).
#
# Prerequisites: iverilog, python3
# =============================================================================

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$RtlDir = Join-Path $ProjectRoot "rtl"
$TbDir  = Join-Path $ProjectRoot "tb"
$SimDir = Join-Path $ProjectRoot "sim"
$DataDir = Join-Path $TbDir "array_scale"

$Sizes = @(4, 8, 16, 32)

# Common RTL source files
$RtlSources = @(
    (Join-Path $RtlDir "pe\fp16_mul.v"),
    (Join-Path $RtlDir "pe\fp16_add.v"),
    (Join-Path $RtlDir "pe\fp32_add.v"),
    (Join-Path $RtlDir "pe\pe_top.v"),
    (Join-Path $RtlDir "common\fifo.v"),
    (Join-Path $RtlDir "common\axi_monitor.v"),
    (Join-Path $RtlDir "common\op_counter.v"),
    (Join-Path $RtlDir "array\reconfig_pe_array.v"),
    (Join-Path $RtlDir "buf\pingpong_buf.v"),
    (Join-Path $RtlDir "power\npu_power.v"),
    (Join-Path $RtlDir "ctrl\npu_ctrl.v"),
    (Join-Path $RtlDir "axi\npu_axi_lite.v"),
    (Join-Path $RtlDir "axi\npu_dma.v"),
    (Join-Path $RtlDir "top\npu_top.v")
)

# Testbench wrappers (generated by gen_tb.py, one per N)
# Each wrapper includes tb_array_scale_body.v

# Ensure sim directory exists
if (-not (Test-Path $SimDir)) { New-Item -ItemType Directory -Path $SimDir | Out-Null }

# Step 0: Generate test data
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  PE Array Scale Verification" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

Write-Host "`n[0/3] Generating test data and wrappers..." -ForegroundColor Yellow
& python (Join-Path $DataDir "gen_data.py")
if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Data generation failed!" -ForegroundColor Red
    exit 1
}

& python (Join-Path $DataDir "gen_tb.py")
if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Wrapper generation failed!" -ForegroundColor Red
    exit 1
}

# Check iverilog
try {
    $ver = & iverilog -V 2>&1 | Select-Object -First 1
    Write-Host "[OK] $ver" -ForegroundColor Green
} catch {
    Write-Host "[ERROR] iverilog not found!" -ForegroundColor Red
    exit 1
}

$totalPass = 0
$totalFail = 0

foreach ($N in $Sizes) {
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host "  K Depth: ${N} (physical PE array in this testbench is 1x1)" -ForegroundColor Cyan

    Write-Host "========================================" -ForegroundColor Cyan

    $VvpOut = Join-Path $SimDir "tb_arr${N}.vvp"
    $NDir = Join-Path $DataDir "N${N}"
    $WrapperFile = Join-Path $NDir "tb_wrapper.v"

    # Step 1: Compile
    Write-Host "`n[1/3] Compiling for N=$N..." -ForegroundColor Yellow

    & iverilog -g2012 `
        -DDUMP_VCD `
        "-I$NDir" `
        -o $VvpOut `
        $RtlSources `
        $WrapperFile

    if ($LASTEXITCODE -ne 0) {
        Write-Host "[ERROR] Compilation failed for N=$N!" -ForegroundColor Red
        $totalFail += 100
        continue
    }
    Write-Host "[OK] Compilation successful." -ForegroundColor Green

    # Step 2: Run simulation
    Write-Host "`n[2/3] Running simulation..." -ForegroundColor Yellow

    Push-Location $ProjectRoot
    $simOutput = & vvp $VvpOut 2>&1
    $simExit = $LASTEXITCODE
    Pop-Location

    # Parse and display output
    $nPass = 0
    $nFail = 0
    foreach ($line in $simOutput) {
        if ($line -match "\[PASS\]") {
            Write-Host $line -ForegroundColor Green
            $nPass++
        } elseif ($line -match "\[FAIL\]") {
            Write-Host $line -ForegroundColor Red
            $nFail++
        } elseif ($line -match "TIMEOUT") {
            Write-Host $line -ForegroundColor Red
            $nFail++
        } elseif ($line -match "####|Array Scale|Running|ALL.*PASSED") {
            Write-Host $line -ForegroundColor Cyan
        } elseif ($line -match "RESULT:") {
            Write-Host $line -ForegroundColor $(if ($nFail -eq 0) { "Green" } else { "Red" })
        } else {
            Write-Host $line
        }
    }

    $totalPass += $nPass
    $totalFail += $nFail

    Write-Host "`n[3/3] N=${N}: ${nPass} PASSED, ${nFail} FAILED" -ForegroundColor $(if ($nFail -eq 0) { "Green" } else { "Red" })
}

# Final Summary
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  FINAL SUMMARY" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Total: ${totalPass} PASSED, ${totalFail} FAILED" -ForegroundColor $(if ($totalFail -eq 0) { "Green" } else { "Red" })
Write-Host "========================================" -ForegroundColor Cyan

if ($totalFail -eq 0) {
    Write-Host "`n  All array sizes verified successfully!" -ForegroundColor Green
} else {
    Write-Host "`n  Some tests failed. Check output above." -ForegroundColor Red
    exit 1
}
