#!/usr/bin/env python3
"""
gen_tb.py - Generate per-K testbench wrappers for tb_array_scale

Creates tb/array_scale/N<K>/tb_wrapper.v that:
  1. Defines module tb_array_scale with K-specific parameters
  2. Hardcodes $readmemh paths (iverilog doesn't support macro expansion in $readmemh)
  3. Includes the common testbench body (tb_array_scale_body.v)

Note: the historical file/module name tb_array_scale is retained,
but the actual verification target is a 1x1 PE with varying K depth.
"""


import os

# Read the common body template
BODY_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                         '..', 'tb_array_scale_body.v')

def gen_wrapper(N, out_dir):
    sub_dir = os.path.join(out_dir, f'N{N}')
    os.makedirs(sub_dir, exist_ok=True)

    dram_hex = os.path.join(sub_dir, 'dram_init.hex')
    exp_hex  = os.path.join(sub_dir, 'expected.hex')

    # Convert to absolute paths with forward slashes (iverilog compatible)
    dram_abs = os.path.abspath(dram_hex).replace('\\', '/')
    exp_abs  = os.path.abspath(exp_hex).replace('\\', '/')

    # Body file is at tb/tb_array_scale_body.v (relative from tb/array_scale/N<N>/)
    body_rel = '../../tb_array_scale_body.v'

    content = f'''// =============================================================================
// Auto-generated testbench wrapper for N={N}
// Generated by gen_tb.py - DO NOT EDIT
// =============================================================================

`timescale 1ns/1ps

module tb_array_scale;

`define N {N}
`include "test_params.vh"

localparam ROWS    = 1;
localparam COLS    = 1;
localparam DATA_W  = 16;
localparam ACC_W   = 32;
localparam CLK_T   = 10;
localparam DRAM_SZ = `DRAM_SIZE;

// NPU AXI-Lite register map
localparam REG_CTRL   = 32'h00;
localparam REG_STATUS = 32'h04;
localparam REG_M_DIM  = 32'h10;
localparam REG_N_DIM  = 32'h14;
localparam REG_K_DIM  = 32'h18;
localparam REG_W_ADDR = 32'h20;
localparam REG_A_ADDR = 32'h24;
localparam REG_R_ADDR = 32'h28;

// ---------------------------------------------------------------------------
// DRAM Model (hardcoded paths - iverilog doesn't expand macros in $readmemh)
// ---------------------------------------------------------------------------
reg [ACC_W-1:0] dram [0:DRAM_SZ-1];
integer dram_i;

initial begin
    for (dram_i = 0; dram_i < DRAM_SZ; dram_i = dram_i + 1)
        dram[dram_i] = 32'h0;
    $readmemh("{dram_abs}", dram);
end

// ---------------------------------------------------------------------------
// Expected results (hardcoded path)
// ---------------------------------------------------------------------------
reg [31:0] expected [0:`NUM_TESTS-1];
integer exp_i;

initial begin
    for (exp_i = 0; exp_i < `NUM_TESTS; exp_i = exp_i + 1)
        expected[exp_i] = 32'h0;
    $readmemh("{exp_abs}", expected);
end


`include "{body_rel}"

endmodule
'''

    with open(os.path.join(sub_dir, 'tb_wrapper.v'), 'w') as f:
        f.write(content)
    print(f"  Generated N{N}/tb_wrapper.v")


def main():
    out_dir = os.path.dirname(os.path.abspath(__file__))
    for N in [4, 8, 16, 32]:
        gen_wrapper(N, out_dir)

if __name__ == '__main__':
    print("Generating testbench wrappers:")
    main()
    print("Done.")
