// AUTO-GENERATED by gen_classifier_data.py ¡ª DO NOT EDIT
// Expected INT32 accumulator outputs for Tiny-FC-Net

localparam DRAM_BASE   = 32'h00001000;
localparam OFF_W1      = 12'h000;
localparam OFF_W2      = 12'h100;
localparam OFF_W3      = 12'h140;
localparam OFF_INPUT   = 12'h200;
localparam OFF_A1      = 12'h300;
localparam OFF_A2      = 12'h380;
localparam OFF_A3      = 12'h3C0;

localparam FC1_M=1, FC1_N=8, FC1_K=16;
localparam FC2_M=1, FC2_N=4, FC2_K=8;
localparam FC3_M=1, FC3_N=4, FC3_K=4;

// Layer 1 expected accumulators (INT32)
localparam EXP_ACC1_0 = 32'h00003D9A;  // 15770
localparam EXP_ACC1_1 = 32'hFFFFDBFC;  // -9220
localparam EXP_ACC1_2 = 32'hFFFFEF66;  // -4250
localparam EXP_ACC1_3 = 32'hFFFFE250;  // -7600
localparam EXP_ACC1_4 = 32'hFFFFF72C;  // -2260
localparam EXP_ACC1_5 = 32'hFFFFDB8E;  // -9330
localparam EXP_ACC1_6 = 32'hFFFFD698;  // -10600
localparam EXP_ACC1_7 = 32'h000040B0;  // 16560

// Layer 1 expected A1 (INT8 after ReLU+shift, packed to 32-bit)
localparam EXP_A1_W0 = 32'h0000003D;
localparam EXP_A1_W1 = 32'h40000000;

// Layer 2 expected accumulators (INT32)
localparam EXP_ACC2_0 = 32'h000018A1;  // 6305
localparam EXP_ACC2_1 = 32'h00001894;  // 6292
localparam EXP_ACC2_2 = 32'h00001B49;  // 6985
localparam EXP_ACC2_3 = 32'h00000F9D;  // 3997

// Layer 2 expected A2 (INT8 after ReLU+shift)
localparam EXP_A2_W0 = 32'h0F1B1818;

// Layer 3 expected final logits (INT32)
localparam EXP_ACC3_0 = 32'h000002F1;  // 753
localparam EXP_ACC3_1 = 32'h0000029D;  // 669
localparam EXP_ACC3_2 = 32'h00000324;  // 804
localparam EXP_ACC3_3 = 32'h00000123;  // 291

// Predicted class
localparam PRED_CLASS = 2;
