// Auto-generated by tb/tile4/gen_tile4_data.py: fp16_4x4x4
`define TEST_NAME "fp16_4x4x4"
`define M_DIM 4
`define N_DIM 4
`define K_DIM 4
`define NUM_RESULTS 16
`define DRAM_SIZE 1024
`define W_ADDR 32'h00000200
`define A_ADDR 32'h00000280
`define R_ADDR 32'h00000300
`define CTRL 32'h00000019
`define IS_FP16 1
`define DRAM_HEX "tb/tile4/fp16_4x4x4/dram_init.hex"
`define EXPECTED_HEX "tb/tile4/fp16_4x4x4/expected.hex"
